FROM node:12.13.0

RUN mkdir -p /opt/administrator

WORKDIR /opt/administrator

# COPY package.json /opt/administrator/package.json

# RUN npm i --registry=https://registry.npm.taobao.org

# COPY . /opt/administrator

EXPOSE 7003

# ENTRYPOINT ["geth"]
CMD npm run start
