install-reveal:
	git clone https://github.com/hakimel/reveal.js.git
	cd reveal.js && npm install --verbose

link-resource:
	ln -s ~/yxd/learning-git/reveal-js/* ~/tmp/reveal.js/

start:
	npm start

curl:
	curl http://localhost:8000
