build-mui:
	npm run build-mui

start-wds:
	webpack-dev-server --inline --hot --config ./material-ui/webpack.config.js --content-base ./material-ui/build/

build-redux:
	npm run build-redux

build-hook:
	npm run build-hook

start-wds-hook:
	npx webpack-dev-server --inline --hot --config ./hook/webpack.config.js --content-base ./hook/build/ --history-api-fallback

req:
	curl -ivL http://localhost:8080