version: '3.5'

services:
  node1:
    build: .
    restart: always
    stdin_open: true
    tty: true
#    links:
#      - tomcatdb:mysql
    command: ["--nodiscover", "--maxpeers=1",
              "--rpc", "--rpcport=8545", "--rpcapi=db,eth,net,web3", "--rpccorsdomain=*",
              "--datadir=/root/.ethereum", "--networkid=15", "--identity=Node1"] #, "console"
    ports:
      - "8545:8545"
      - "30303:30303"
#      - "30303:30303/udp"
#    environment:
#      TOMCAT_DB_HOST: tomcatdb
#    volumes:
#      - type: volume
#        source: joomla
#      - type: bind
#        source: ./data #/Users/xiaodongyu/Learning/learning-git/ethereum/ethereumprivate/data
#        target: /root/.ethereum

#volumes:
#  node1:
#  node2:
