version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: mysqlpass
    volumes:
      - '/opt/ehomeguru/docker/joomla:/var/www/html'

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
    volumes:
      - '/opt/ehomeguru/docker/mysql:/var/lib/mysql'
