a:
	curl -X POST -d '{"api_name": "stock_basic", "token": "b85254a8d942276a15c01626314b5a0efe4348fd88bdc19186560228", "params": {"list_stauts":"L"}, "fields": "ts_code,symbol,name,area,industry,list_date"}' http://api.tushare.pro

b:
	curl -X POST -d '{"api_name": "daily", "token": "b85254a8d942276a15c01626314b5a0efe4348fd88bdc19186560228", "params": {"ts_code:"000001.SZ"}, "fields": "ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount"}' http://api.tushare.pro
