version: '3.5'

services:
  joomla:
    build: .
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8000:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: mysqlpass
      JOOMLA_DB_NAME: joomla_ehg
    volumes:
#      - type: volume
#        source: joomla
      - type: bind
        source: /Users/xiaodongyu/tmp/volume/joomlaehg_joomla
        target: /var/www/html

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

volumes:
  joomla:
  mysql:
