start-node:
	fibos fibos_node/node.js

start-fibos-repl:
	fibos

start-client:
	fibos fibos_client/client.js

create-account:
	fibos fibos_client/createAccount.js

query-account:
	fibos fibos_client/queryAccount.js

deploy-contract:
	fibos fibos_client/deploy_contract.js

call-contract:
	fibos fibos_client/call_contract.js